INSERT INTO slot_definition(slot_key, slot_name, source, is_active)
VALUES
  ('address', '地址', 'mcp_seed', TRUE),
  ('amount', '金额', 'mcp_seed', TRUE),
  ('arr_airport', '到达机场', 'mcp_seed', TRUE),
  ('bank', '银行', 'mcp_seed', TRUE),
  ('city', '城市', 'mcp_seed', TRUE),
  ('crop_bbox', '裁剪框', 'mcp_seed', TRUE),
  ('date', '日期', 'mcp_seed', TRUE),
  ('dep_airport', '出发机场', 'mcp_seed', TRUE),
  ('destination', '目的地', 'mcp_seed', TRUE),
  ('draw_color', '绘制颜色', 'mcp_seed', TRUE),
  ('express_no', '快递单号', 'mcp_seed', TRUE),
  ('flight_no', '航班号', 'mcp_seed', TRUE),
  ('geo_point', '经纬度', 'mcp_seed', TRUE),
  ('image_url', '图片链接', 'mcp_seed', TRUE),
  ('ip', 'IP地址', 'mcp_seed', TRUE),
  ('issue_no', '期号', 'mcp_seed', TRUE),
  ('line_thickness', '线宽', 'mcp_seed', TRUE),
  ('lottery_id', '彩票ID', 'mcp_seed', TRUE),
  ('lottery_number', '彩票号码', 'mcp_seed', TRUE),
  ('org_code', '主体编码', 'mcp_seed', TRUE),
  ('org_name', '主体名称', 'mcp_seed', TRUE),
  ('origin', '出发地', 'mcp_seed', TRUE),
  ('page_no', '页码', 'mcp_seed', TRUE),
  ('query_text', '查询文本', 'mcp_seed', TRUE),
  ('ref_name', '引用名称', 'mcp_seed', TRUE),
  ('result_limit', '结果数量', 'mcp_seed', TRUE),
  ('shipper_code', '快递公司编码', 'mcp_seed', TRUE),
  ('sort_by', '排序方式', 'mcp_seed', TRUE),
  ('symbol', '标的代码', 'mcp_seed', TRUE),
  ('timezone', '时区', 'mcp_seed', TRUE),
  ('zipcode', '邮编', 'mcp_seed', TRUE)
ON CONFLICT (slot_key) DO UPDATE
SET slot_name = EXCLUDED.slot_name,
    source = EXCLUDED.source,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();

