CREATE TABLE IF NOT EXISTS agent_log_event (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key',
  event_time DATETIME(3) NOT NULL COMMENT 'log event time',
  ingest_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'mysql ingest time',
  app_name VARCHAR(64) NOT NULL COMMENT 'service/application name',
  module_name VARCHAR(64) DEFAULT NULL COMMENT 'module name, e.g. agent-ops/agent-business',
  env_name VARCHAR(32) DEFAULT NULL COMMENT 'environment, e.g. dev/test/prod',
  host_name VARCHAR(128) DEFAULT NULL COMMENT 'host or node name',
  level VARCHAR(16) NOT NULL COMMENT 'log level',
  logger_name VARCHAR(255) DEFAULT NULL COMMENT 'logger name',
  thread_name VARCHAR(128) DEFAULT NULL COMMENT 'thread name',
  trace_id VARCHAR(64) DEFAULT NULL COMMENT 'request trace id',
  task_id VARCHAR(64) DEFAULT NULL COMMENT 'cross-request task id',
  service_name VARCHAR(128) DEFAULT NULL COMMENT 'service name from TaskContext',
  method_name VARCHAR(128) DEFAULT NULL COMMENT 'method/task name from TaskContext',
  event_type VARCHAR(64) DEFAULT NULL COMMENT 'log event type, e.g. EXECUTOR_REJECTED',
  pool_type VARCHAR(64) DEFAULT NULL COMMENT 'executor pool type',
  pool_name VARCHAR(128) DEFAULT NULL COMMENT 'executor pool name',
  message TEXT NOT NULL COMMENT 'log message',
  exception_class VARCHAR(255) DEFAULT NULL COMMENT 'exception class',
  stack_trace MEDIUMTEXT DEFAULT NULL COMMENT 'stack trace',
  mdc_json JSON DEFAULT NULL COMMENT 'full mdc map snapshot',
  ext_json JSON DEFAULT NULL COMMENT 'extra business fields',
  kafka_topic VARCHAR(128) DEFAULT NULL COMMENT 'source kafka topic',
  kafka_partition INT DEFAULT NULL COMMENT 'source kafka partition',
  kafka_offset BIGINT DEFAULT NULL COMMENT 'source kafka offset',
  PRIMARY KEY (id),
  KEY idx_event_time (event_time),
  KEY idx_ingest_time (ingest_time),
  KEY idx_level_time (level, event_time),
  KEY idx_trace_id (trace_id),
  KEY idx_task_id (task_id),
  KEY idx_event_type_time (event_type, event_time),
  KEY idx_pool_time (pool_type, pool_name, event_time),
  UNIQUE KEY uk_kafka_pos (kafka_topic, kafka_partition, kafka_offset)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='unified app logs consumed from kafka';
